---
title: "CUNY SPS DATA 621 - CTG5 - Final"
author: "Betsy Rosalen, Gabrielle Bartomeo, Jeremy O'Brien, Lidiia Tronina, Rose Koh"
date: "May 23rd, 2019"
output:
    bookdown::pdf_document2:
        toc: true
        toc_depth: 2
        number_sections: true
        fig_width: 5
        fig_height: 4
        fig_caption: true
        includes:  
            in_header: ./source/figure_placement.tex
        highlight: haddock
        df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = FALSE, echo=FALSE, message=FALSE, warning=FALSE)
chooseCRANmirror(graphics=FALSE, ind=1)
source("./source/libs.R")
source("./source/script.R")
source("./source/captioner.R")
#set.seed(123)
```


\newpage


# DATA EXPLORATION

```{r}
str(data)

# library(summarytools)
# st_options(bootstrap.css = FALSE, plain.ascii = FALSE, style = "rmarkdown", dfSummary.silent = TRUE, footnote = NA, subtitle.emphasis = FALSE) 
# summarytools::dfSummary(data, style = 'grid', graph.magnif = 0.75, tmp.img.dir = "/tmp")

```


\newpage


# DATA PREPARATION

```{r}

# Split data into test and train using cross-validation


# Bootstrap surrogate data using synthpop


```

\newpage


# BUILD MODELS

```{r}

# See notes in literature reviewed and Kaggle projects for suggestions on variable selection and feature engineering for models (links TBC)

# See also notes on setup and packages for decision tree, random forest, SVM, and Naive Bayes  (links TBC)

# Break out in sections

# Logistic regression


# Decision tree (CHAID or C&RT?)


# Random forest


# Support Vector Machines


# Naive Bayes




```

\newpage


# SELECT MODELS

```{r}


```

\newpage


# Appendix

The appendix is available as script.R file in `projectFinal_heart` folder.

https://github.com/betsyrosalen/DATA_621_Business_Analyt_and_Data_Mining

```
```