
### PLEASE ADD NEW PACKAGES IN ALPHABETICAL ORDER SO WE DON'T DUPLICATE LINES! ###
if (!require('car')) (install.packages('car'))
if (!require('caret')) (install.packages('caret'))
if (!require('caTools')) (install.packages('caTools'))
if (!require('corrplot')) (install.packages('corrplot'))
if (!require('data.table')) (install.packages('data.table'))
if (!require('DataExplorer')) (install.packages('DataExplorer'))
if (!require('doMC')) (install.packages('doMC'))
if (!require('dplyr')) (install.packages('dplyr'))
if (!require('e1071')) (install.packages('e1071'))
if (!require('faraway')) (install.packages('faraway'))
if (!require('GGally')) (install.packages('GGally'))
if (!require('ggfortify')) (install.packages('ggfortify'))
if (!require('ggplot2')) (install.packages('ggplot2'))
if (!require('gridExtra')) (install.packages('gridExtra'))
if (!require('huxtable')) (install.packages('huxtable'))
if (!require('jtools')) (install.packages('jtools'))
if (!require('kableExtra')) (install.packages('kableExtra'))
if (!require('kernlab')) (install.packages('kernlab'))
if (!require('MASS')) (install.packages('MASS'))
if (!require('mlbench')) (install.packages('mlbench'))
if (!require('pROC')) (install.packages('pROC'))
if (!require('pscl')) (install.packages('pscl'))
if (!require('psych')) (install.packages('psych'))
if (!require('randomForest')) (install.packages('randomForest'))
if (!require('reshape2')) (install.packages('reshape2'))
if (!require('rfUtilities')) (install.packages('rfUtilities'))
if (!require('ROCR')) (install.packages('ROCR'))
if (!require('rstan')) (install.packages('rstan'))
if (!require('synthpop')) (install.packages('synthpop'))
if (!require('tidyverse')) (install.packages('tidyverse'))
if (!require('tidyr')) (install.packages('tidyr'))

